<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyName>lstwoMODS_WobblyLife</AssemblyName>
        <Description></Description>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <Optimize>True</Optimize>
        <DebugType>full</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <Optimize>False</Optimize>
        <DebugType>full</DebugType>
    </PropertyGroup>

    <ItemGroup>

        <PackageReference Include="WobblyLife.GameLibs" Version="1.0.0.4" >
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>

        <Reference Include="CustomItems">
            <HintPath>lib\CustomItems.dll</HintPath>
        </Reference>

        <Reference Include="lstwoMODS_Core">
            <HintPath>lib\lstwoMODS_Core.dll</HintPath>
            <DocumentationFile>lib\lstwoMODS_Core.xml</DocumentationFile>
        </Reference>

        <Reference Include="lstwoMODS.ImGui.Shared">
            <HintPath>lib\lstwoMODS.ImGui.Shared.dll</HintPath>
        </Reference>

        <Reference Include="CinematicUnityExplorer.BIE5.Mono">
            <HintPath>lib\CinematicUnityExplorer.BIE5.Mono.dll</HintPath>
        </Reference>
        
        <Reference Include="System.Runtime.CompilerServices.Unsafe">
            <HintPath>lib\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
        </Reference>

        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
        <PackageReference Include="UnityEngine.Modules" Version="2020.3.44" IncludeAssets="compile" />
        <PackageReference Include="UniverseLib.Mono" Version="1.5.1" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\piracy2.png" />
        <EmbeddedResource Include="Resources\piracy_emotes.png" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\lstwoMODS.WobblyLife.SharedObjects\lstwoMODS.WobblyLife.SharedObjects.csproj" />
    </ItemGroup>
</Project>
